package tree;

import models.Device;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.ArrayList;
import java.util.List;

public class UsageTree {

  //creating node 
    private static class Node {
        Device device;      
        double dailyKwh;    //the key 
        Node left;           
        Node right;         

        Node(Device device, double dailyKwh) {
            this.device   = device;
            this.dailyKwh = dailyKwh;
            this.left     = null;
            this.right    = null;
        }
    }

    
    private Node root;   
    private int  size;   // no. od devices 
    
    public UsageTree() {
        this.root = null;
        this.size = 0;
    }

//insert a device into the tree 
    public void insert(Device device, double dailyKwh) {
        root = insertRec(root, device, dailyKwh);
        size++;
    }

   
    private Node insertRec(Node current, Device device, double dailyKwh) {
    
        if (current == null) {
            return new Node(device, dailyKwh);
        }

        if (dailyKwh < current.dailyKwh) {

            current.left = insertRec(current.left, device, dailyKwh);
        } else if (dailyKwh > current.dailyKwh) {
           
            current.right = insertRec(current.right, device, dailyKwh);
        } else {
           
            current.right = insertRec(current.right, device, dailyKwh);
        }

        return current;
    }

    public void inOrderDisplay() {
        if (root == null) {
            System.out.println("  [Usage tree is empty — no devices added yet]");
            return;
        }
        System.out.println("\n  === Devices: Lowest → Highest Daily Usage ===");
        System.out.printf("  %-20s %-12s %-10s%n", "Device Name", "Category", "Daily kWh");
        System.out.println("  " + "─".repeat(45));
        inOrderRec(root);
    }

    
    private void inOrderRec(Node current) {
        if (current == null) return;           // base case: leaf's child

        inOrderRec(current.left);             
        printNode(current);                   
        inOrderRec(current.right);             
    }

    private void printNode(Node node) {
        System.out.printf("  %-20s %-12s %.3f kWh%n",
                node.device.getName(),
                node.device.getCategory(),
                node.dailyKwh);
    }

    //get the sorted list by the daily kwd 
    public List<Device> getSortedDevices() {
        List<Device> result = new ArrayList<>();
        collectInOrder(root, result);
        return result;
    }

    private void collectInOrder(Node current, List<Device> result) {
        if (current == null) return;
        collectInOrder(current.left, result);
        result.add(current.device);
        collectInOrder(current.right, result);
    }

   //finding the highest consumer 
    public Device getHighestConsumer() {
        if (root == null) return null;

        Node current = root;
        while (current.right != null) {
            current = current.right;   // keep going right
        }
        return current.device;
    }

  //finding the lowest consumer 
    public Device getLowestConsumer() {
        if (root == null) return null;

        Node current = root;
        while (current.left != null) {
            current = current.left;    // keep going left
        }
        return current.device;
    }

   
    public void exportReport(String filename) {
        // Collect sorted devices first
        List<Device> sorted = getSortedDevices();

        if (sorted.isEmpty()) {
            System.out.println("  [No data to export — tree is empty]");
            return;
        }

        // Try-with-resources: automatically closes the file even if error occurs
        try (PrintWriter writer = new PrintWriter(new FileWriter(filename))) {

            writer.println("========================================");
            writer.println("   SMART ENERGY TRACKER — USAGE REPORT");
            writer.println("========================================");
            writer.printf("%-20s %-12s %-10s%n", "Device Name", "Category", "Daily kWh");
            writer.println("─".repeat(45));

            for (Device d : sorted) {
                // We need kWh — re-traverse to get it
                writeDeviceKwh(root, d.getName(), writer);
            }

            writer.println("─".repeat(45));
            writer.println("Report generated by SmartEnergyTracker — Member 4");

            System.out.println("  ✓ Report exported to: " + filename);

        } catch (IOException e) {
            System.out.println("  [Error writing report: " + e.getMessage() + "]");
        }
    }

   
    private void writeDeviceKwh(Node current, String name, PrintWriter writer) {
        if (current == null) return;
        if (current.device.getName().equals(name)) {
            writer.printf("%-20s %-12s %.3f kWh%n",
                    current.device.getName(),
                    current.device.getCategory(),
                    current.dailyKwh);
            return;
        }
        writeDeviceKwh(current.left,  name, writer);
        writeDeviceKwh(current.right, name, writer);
    }

    
    public int getSize() {
        return size;
    }

    public boolean isEmpty() {
        return root == null;
    }

    public void clear() {
        root = null;
        size = 0;
    }
}
